name: "Directory Blacklist Action"
description: "Action that checks if a specific directory was commited"
author: "Locour"

inputs:
  BLACKLISTED_DIR:
    description: "Directory that is blacklisted"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"